spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/insta_clone_db
    username: insta_clone_user
    password: 1qaz2wsx
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 1r1et1rv9ckjekg18jg8j0rogq
            client-secret: 12golp9e8kf2fvablmdpon1jbl2nkcel1j65vjckd4qj0frisd44
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: your_clientName
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_zR0hloKwB
            user-name-attribute: cognito:username
lk:
  ijse:
    ws:
      jwt:
        userPoolId: "eu-west-1_zR0hloKwB"
        region: "eu-west-1"
        jwk-url: "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_zR0hloKwB/.well-known/jwks.json"
        user-name-field: "username"